### ISSUE TITLE
how to add convert=true in the upload url 

### ISSUE THREAD

**Issue by shadowhunter2009** [mschilli/net-google-drive-simple#12]
I want to make my pipe line automatically. 

Uploading the csv file, convert it into spreadsheet, and then run app script on that.

One issue is that how could I add convert=true to the upload url.

**Comment by mschilli** [comment]
Is this a documented feature?

**Comment by shadowhunter2009** [comment]
From google? It is documented for sure.

**Comment by shadowhunter2009** [comment]
Hi, any updates on this?

**Comment by mschilli** [comment]
I was hoping you'd point me to the documentation you were referring to.

**Comment by shadowhunter2009** [comment]
the following is the one. 

https://developers.google.com/drive/v2/reference/files/insert

**Comment by mschilli** [comment]
file_upload() should do exactly what you need:

    http://search.cpan.org/~mschilli/Net-Google-Drive-Simple-0.12/lib/Net/Google/Drive/Simple.pm
