### ISSUE TITLE
internal method http_loop claims to use $self->init() to refresh token

### ISSUE THREAD

**Issue by Pachelbel1414** [mschilli/net-google-drive-simple#37]
internal method http_loop claims to use $self->init() to refresh token.

$self->init() does nothing if already inited, so I don't think this is doing what it's supposed to.

since the request (with the token) has already been generated by the caller, I think you should do something like the following after the sleep in the retry logic:

if ( --$RETRIES >= 0 ) {
   ERROR "Retrying in $SLEEP_INTERVAL seconds";
   sleep $SLEEP_INTERVAL;
   $req->header( $self->{oauth}->authorization_headers() );   # refresh the token if needed
   redo;
}

**Comment by atoomic** [comment]
thanks for the report, I applied it as 304a6f04b02a0bf2154598c38d3996b447c5ff20
