### ISSUE TITLE
Upgrade to drive API v3?

### ISSUE THREAD

**Issue by hakonhagland** [mschilli/net-google-drive-simple#46]
Any plans of upgrading to API version 3? See [this](https://developers.google.com/drive/api/v2/v3versusv2) page for an overview of differences between v2 and v3.

**Comment by atoomic** [comment]
We should definitively consider updating to use the v3.

**Comment by xsawyerx** [comment]
V3 is now available at #55.

**Comment by atoomic** [comment]
this is now available with v3.00
